
package project_or;

import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class main_project extends javax.swing.JFrame {


    CardLayout card;
    public main_project() {
        initComponents();
        setSize(810,600);
               setLocationRelativeTo(null);
        card = new CardLayout();
        panal_card.setLayout(card);
        panal_card.add("graph",new panal_graph());
        panal_card.add("dual", new panal_dual());
        panal_card.add("main", new main_panal());
        panal_card.add("about", new about_panal());
        card.show(panal_card, "main");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panal_card = new javax.swing.JPanel();
        label_home = new javax.swing.JLabel();
        label_main = new javax.swing.JLabel();
        label_simplex = new javax.swing.JLabel();
        label_graph = new javax.swing.JLabel();
        label_dual = new javax.swing.JLabel();
        label_ass = new javax.swing.JLabel();
        label_about = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        javax.swing.GroupLayout panal_cardLayout = new javax.swing.GroupLayout(panal_card);
        panal_card.setLayout(panal_cardLayout);
        panal_cardLayout.setHorizontalGroup(
            panal_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        panal_cardLayout.setVerticalGroup(
            panal_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(panal_card);
        panal_card.setBounds(10, 30, 590, 500);

        label_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/2/5.png"))); // NOI18N
        jPanel1.add(label_home);
        label_home.setBounds(0, 0, 800, 560);

        label_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_mainMouseClicked(evt);
            }
        });
        jPanel1.add(label_main);
        label_main.setBounds(640, 40, 150, 60);

        label_simplex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_simplexMouseClicked(evt);
            }
        });
        jPanel1.add(label_simplex);
        label_simplex.setBounds(640, 120, 150, 60);

        label_graph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_graphMouseClicked(evt);
            }
        });
        jPanel1.add(label_graph);
        label_graph.setBounds(644, 204, 140, 60);

        label_dual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_dualMouseClicked(evt);
            }
        });
        jPanel1.add(label_dual);
        label_dual.setBounds(640, 290, 150, 50);

        label_ass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_assMouseClicked(evt);
            }
        });
        jPanel1.add(label_ass);
        label_ass.setBounds(640, 370, 150, 60);

        label_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_aboutMouseClicked(evt);
            }
        });
        jPanel1.add(label_about);
        label_about.setBounds(640, 450, 150, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_graphMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_graphMouseClicked

card.show(panal_card, "graph");
// TODO add your handling code here:
    }//GEN-LAST:event_label_graphMouseClicked

    private void label_dualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dualMouseClicked

card.show(panal_card, "dual");        
// TODO add your handling code here:
    }//GEN-LAST:event_label_dualMouseClicked

    private void label_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_aboutMouseClicked

        
card.show(panal_card, "about");        
        try {
            Desktop.getDesktop().open(new File(getClass().getResource("DOC.pdf").getPath()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_label_aboutMouseClicked

    private void label_simplexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_simplexMouseClicked

      //  try {
            //Desktop.getDesktop().open(new File(getClass().getResource("Simplex by the Z way.exe").getPath()));
       /* String path = "Simplex by the Z way.exe";
File file = new File(path);
if (! file.exists()) {
   throw new IllegalArgumentException("The file " + path + " does not exist");
}
Process p = Runtime.getRuntime().exec(file.getAbsolutePath());*/
        /*    Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " +"C:\\Users\\Enjoy\\Documents\\NetBeansProjects\\project_or\\src\\project_or\\SimplexbytheZway.exe");
        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }*/
        try {
            Desktop.getDesktop().open(new File(getClass().getResource("SimplexbytheZway.exe").getPath()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_label_simplexMouseClicked

    private void label_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_mainMouseClicked

card.show(panal_card, "main");        
// TODO add your handling code here:
    }//GEN-LAST:event_label_mainMouseClicked

    private void label_assMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_assMouseClicked
/*try{
            Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " +"C:\\Users\\Enjoy\\Documents\\NetBeansProjects\\project_or\\src\\project_or\\AssignmentProblems.exe");
        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }*/
  try {
            Desktop.getDesktop().open(new File(getClass().getResource("AssignmentProblems.exe").getPath()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }      
// TODO add your handling code here:
    }//GEN-LAST:event_label_assMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_about;
    private javax.swing.JLabel label_ass;
    private javax.swing.JLabel label_dual;
    private javax.swing.JLabel label_graph;
    private javax.swing.JLabel label_home;
    private javax.swing.JLabel label_main;
    private javax.swing.JLabel label_simplex;
    private javax.swing.JPanel panal_card;
    // End of variables declaration//GEN-END:variables
}
