/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_or;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Enjoy
 */
public class panal_dual extends javax.swing.JPanel {

    /**
     * Creates new form panal_dual
     */ 
    static JFrame f;
    public panal_dual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panal_home = new javax.swing.JPanel();
        button_ok = new javax.swing.JButton();
        txt_var = new javax.swing.JTextField();
        txt_con = new javax.swing.JTextField();
        panal_comp = new javax.swing.JPanel();
        label_s1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_s2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        panal_home.setBackground(new java.awt.Color(36, 36, 36));

        button_ok.setText("OK");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        txt_var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_varActionPerformed(evt);
            }
        });
        txt_var.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_varKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_varKeyReleased(evt);
            }
        });

        txt_con.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_conKeyReleased(evt);
            }
        });

        panal_comp.setLayout(null);

        label_s1.setBackground(new java.awt.Color(255, 255, 255));
        label_s1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_s1.setForeground(new java.awt.Color(255, 255, 255));

        txta_s2.setColumns(20);
        txta_s2.setRows(5);
        jScrollPane1.setViewportView(txta_s2);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Number of variable");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of constrains ");

        javax.swing.GroupLayout panal_homeLayout = new javax.swing.GroupLayout(panal_home);
        panal_home.setLayout(panal_homeLayout);
        panal_homeLayout.setHorizontalGroup(
            panal_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panal_homeLayout.createSequentialGroup()
                .addGroup(panal_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panal_homeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panal_comp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panal_homeLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txt_var, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_con, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_ok)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panal_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_s1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        panal_homeLayout.setVerticalGroup(
            panal_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panal_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panal_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txt_con)
                    .addComponent(txt_var)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(panal_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panal_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panal_homeLayout.createSequentialGroup()
                        .addComponent(label_s1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panal_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panal_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
int a=Integer.parseInt(txt_var.getText());
int b=Integer.parseInt(txt_con.getText());

Dualconvert ss = new Dualconvert(a, b);
      //  ss.setVisible(true);        
panal_comp.add(ss.largepanel);
        repaint();

// TODO add your handling code here:
    }//GEN-LAST:event_button_okActionPerformed

    private void txt_varActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_varActionPerformed

        

// TODO add your handling code here:
    }//GEN-LAST:event_txt_varActionPerformed

    private void txt_varKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_varKeyPressed
//        String a=txt_var.getText();
//         System.out.println("");
//        if(valid(a)==0){
//        
//            txt_var.setBackground(Color.red);
//        }else
//            txt_var.setBackground(Color.white);
//        
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_varKeyPressed

    private void txt_varKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_varKeyReleased
         String a=txt_var.getText();
         
        if(valid(a)==0){
        button_ok.setEnabled(false);
            txt_var.setBackground(Color.red);
        }else{
            txt_var.setBackground(Color.white);
        button_ok.setEnabled(true);
        }
    }//GEN-LAST:event_txt_varKeyReleased

    private void txt_conKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_conKeyReleased

String a=txt_con.getText();

        if(valid(a)==0){
button_ok.setEnabled(false);        
           txt_con.setBackground(Color.red);
        }else{
button_ok.setEnabled(true);
            txt_con.setBackground(Color.white);        
    }
// TODO add your handling code here:
    }//GEN-LAST:event_txt_conKeyReleased
    public static void main(String[] args) {
        
       f=new JFrame();
       System.out.println(valid("hgt5"));
        f.setSize(1160 , 612);
        f.setLocationRelativeTo(null);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.add(new panal_dual());
        f.setVisible(true);
       
    }
    
    static int valid(String s){
        if(s.matches("[0-9]+"))
            return 1;
        
        return 0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel label_s1;
    private javax.swing.JPanel panal_comp;
    public static javax.swing.JPanel panal_home;
    private javax.swing.JTextField txt_con;
    private javax.swing.JTextField txt_var;
    public static javax.swing.JTextArea txta_s2;
    // End of variables declaration//GEN-END:variables
}
